### PR TITLE
New pages, general tune-ups

### LINKED ISSUE #13: There's... no information on the website.
This is partially to test the issues feature, since I've never used it before, but is still a bit of a problem lol

### PR DESCRIPTION
**Pull request by iosenberg**
Added an about page, and a contact page. Added a navbar. Fixed dir.main to main.

Please, someone who's better at website design fix the CSS.

### CODE REVIEW

**Comment by iosenberg** [comment]
This pull request will pass the lint test once @Aurelius333 's pull request fixing the linter is merged lol

**Comment by iosenberg** [comment]
@Aurelius333 any idea why this is still failing the linter?

**Comment by AjaiKN** [comment]
> @Aurelius333 any idea why this is still failing the linter?

We probably need to fix the merge conflict.

**Comment by iosenberg** [comment]
> 

Ahhhh I cannot read. Thank you lol

**Review by AjaiKN — APPROVED** [review]

**Pull request merged**
