### PR TITLE
react makeover + landing page

### PR DESCRIPTION
**Pull request by yen-mai-codes**
reactjs makeover 
- landing page

### CODE REVIEW

**Comment by iosenberg** [comment]
@yen-mai-codes If you haven't already, you might want to check out this repository:
[https://github.com/gitname/react-gh-pages/tree/master](https://github.com/gitname/react-gh-pages/tree/master)
It has a guide on how to set up react for a github pages website, and has an example pages website set up with react.
I suspect we don't want all 29,000 lines of react on our repository :)

**Comment by yen-mai-codes** [comment]
> @yen-mai-codes If you haven't already, you might want to check out this repository: https://github.com/gitname/react-gh-pages/tree/master It has a guide on how to set up react for a github pages website, and has an example pages website set up with react. I suspect we don't want all 29,000 lines of react on our repository :)

Thanks ike! I will definitely check it out :)

**Comment by wknowleskellett** [comment]
Hi @yen-mai-codes, I'm eager to bring in this pull request when it's ready!

As far as how to go forward from here: I recommend porting the site to React and have that alone be your first pull request, before you start to make changes to the site content. That way we can separate this pull request into two conversations:

- is the conversion to React implemented correctly
- what should the new website look like

I think converting to React is something we can quickly get out of the way, and it opens the door to more people working on the website, while minimizing merge conflicts. Until that step is done, every pull request you do is going to be littered with merge conflicts.

Ping me in this chat if you have git questions:) A clean set of commits can make approving a pull request very fast.

**Comment by wknowleskellett** [comment]
I'm closing this pull request because of #32. The only differences between the two PR's: #32 is pulled into a new branch, and does not have merge conflicts with `main`.

Please pull changes from the `react-update` branch (which should have no conflicts unless you've made a `Makefile` or edited the `README.md` or something).

Future pull requests for this project should all go to the `react-update` branch until we're ready to merge with `main`.

**Pull request closed without merging**
